-- ============================================================
--  AI Agent Marketplace — Seed Data
--  Run AFTER schema.sql in Supabase SQL Editor
-- ============================================================

-- ── USE CASES ───────────────────────────────────────────────
insert into use_cases (id, name, short_desc, tagline, status, color, group_id, output_desc, agent_ids, shared_ids, sort_order) values

('tc-gen', 'Requirement to Test Case Generation',
 'Reads a JIRA Change Request, generates a complete Test Plan with all test cases, and uploads it back to JIRA — ready for the Test Data pipeline to pick up.',
 'When a developer raises a Change Request in JIRA, this pipeline kicks off automatically. It reads the CR, understands what changed, looks up how the team has tested similar things before, drafts the test cases in the designer''s preferred format and style, runs a quality check, gets the designer''s sign-off, and uploads the final Test Plan — an Excel file containing all test cases — directly back to the JIRA ticket. That uploaded Test Plan is then the starting point for the Test Data Generation pipeline.',
 'active', '#2E308E', 'p1',
 'Test Plan (Excel file with all test cases) uploaded directly to the JIRA Change Request — ready for the Test Data Generation pipeline to pick up.',
 array['master-orch','pipeline-orch','jira-connector','cr-summarizer','rag-retrieval','designer-memory','tc-generator','quality-reviewer','designer-feedback','parser-formatter','jira-writer'],
 array['jira-connector','master-orch','pipeline-orch'], 1),

('td-gen', 'Test Data Generation',
 'Picks up the Test Plan from JIRA, enriches every test case with real data credentials from the backend systems, and uploads the updated Test Plan back to JIRA.',
 'The Test Plan uploaded to JIRA by the previous pipeline is this pipeline''s starting point. It reads the Test Plan directly from the JIRA ticket, works out what data each test case needs — MSISDNs, SIM references, port numbers, dealer credentials — queries the backend systems to fetch real, validated values, creates the necessary customer records where needed, confirms every piece of data is working, and writes it all back into the Test Plan. The updated Test Plan — now containing both test cases and all their data credentials — is then uploaded back to the same JIRA ticket, ready for the testing team to execute immediately.',
 'planned', '#0AA8AC', 'p2',
 'Updated Test Plan uploaded back to JIRA — same file now containing test cases and all live test data credentials, one row per test case, ready to execute.',
 array['tc-reader','db-lookup','xml-builder','eai-push','data-validator','data-writer','jira-writer'],
 array['pipeline-orch'], 2),

('defect', 'JIRA Defect Identification (PDI RCA)',
 'When defects are raised in JIRA, understanding where they came from, why they happened, and what else might be affected requires investigation. This use case automates that investigation process.',
 'PDI tickets can be raised in JIRA or in HPSM (HP Service Manager), depending on where the incident was logged. This pipeline reads defect tickets from both systems, classifies the root cause of each one using the team''s existing RCA taxonomy, traces each defect back to the Change Request that introduced it, assesses which other modules could be affected, and posts a detailed RCA analysis report back into both JIRA and HPSM — closing the loop from incident raised to root cause documented.',
 'exploring', '#9333EA', 'defect',
 'Detailed RCA analysis report posted back to both JIRA and HPSM — root cause for each PDI, impact assessment, and pattern findings.',
 array['hpsm-jira-fetcher','rca-analyser','rca-report-gen','ticket-writer'],
 array[]::text[], 3),

('auto-scripts', 'Automation Script Generation',
 'For test cases that can be run by a machine rather than a human, this use case writes the automation code automatically — removing the need for an engineer to manually author Robot Framework scripts.',
 'Not every test case needs a human to run it. Many tests follow a predictable sequence of steps — open this screen, enter this value, click this button, check this result — which a script can repeat reliably hundreds of times without error or fatigue. Writing those scripts manually is time-consuming and requires a skilled automation engineer. This pipeline reads the completed test case and test data Excel from Pipeline 2, goes through each test case and decides whether it can realistically be automated, and then writes the Robot Framework script for every one that can. The scripts are written in small focused batches to maintain quality, each is checked for correctness, each is linked back to its test case ID in the Excel, and everything is packaged together into a single deliverable. Test cases that genuinely need a human — for example, ones requiring physical SIM insertion or visual UI judgment — are flagged clearly as manual.',
 'planned', '#7373D8', 'p3',
 'A set of Robot Framework automation script files, one for each automatable test case, plus the final Excel file updated with a reference to each script. Everything packaged together and ready for the automation team to run.',
 array['jira-connector','automability-checker','script-generator','path-resolver','syntax-validator','jira-writer','tester-feedback'],
 array['jira-connector','jira-writer'], 4),

('dsr', 'Automating DSR Reports',
 'Every working day, the team produces a Daily Status Report showing what was completed, what is in progress, and what is pending. This is currently done manually by pulling data from JIRA and filling in a PowerPoint template. This use case automates the entire process.',
 'At the end of each day, someone on the team opens JIRA, reviews the current state of all tickets and Change Requests, works out what moved forward since yesterday, writes a summary paragraph, opens the DSR PowerPoint template, fills in the date and the status numbers, types in the summary, saves it, and emails it to the management chain. This is repeated every single working day. This pipeline replaces that entire routine. It connects to JIRA, pulls the current state of all tracked items, compares it against what the state was at the end of the previous day, calculates what changed — how many CRs moved to a new stage, how many defects were raised, what is currently blocked — writes the summary in plain English, opens the DSR PowerPoint template and fills in all the details, and sends the completed report by email to the distribution list. The whole process runs automatically at a configured time each day.',
 'pipeline', '#1D9E5C', 'dsr',
 'A completed Daily Status Report PowerPoint file with the current date, updated ticket counts, progress summary, and any highlights — sent automatically to the management distribution list.',
 array['jira-puller','delta-calc','dsr-narrative','ppt-builder','email-dispatch'],
 array['jira-puller','ppt-builder','email-dispatch'], 5),

('mom', 'Auto Generation of Minutes of Meeting',
 'After every team meeting, someone has to write up the minutes — who attended, what was discussed, what decisions were made, and who is responsible for what. This use case does that automatically from a recording or from rough notes.',
 'After a meeting, the organiser or a designated team member has to sit down and write the minutes from memory or from quick notes taken during the call. They need to remember or re-listen to what decisions were made, who owns each action item, and what questions were left open. Then they format it into the standard minutes template and email it to everyone who attended. This pipeline handles all of that. If someone records the meeting audio, the agent converts the speech to text. It then identifies who said what based on the list of attendees. It reads through the transcript and extracts the key content — agenda items covered, decisions taken, each action item with its owner and due date, and any open questions not yet resolved. It formats everything into the standard minutes-of-meeting layout and shares the draft with the meeting organiser for a quick check. Once confirmed, it sends the final minutes to all attendees by email.',
 'pipeline', '#DC2626', 'mom',
 'A formatted minutes-of-meeting document covering attendees, a summary of each agenda item discussed, a list of decisions made, an action items table showing owner, task, and due date for each item, and any open questions — sent to all meeting attendees.',
 array['audio-ingestion','transcription','speaker-id','mom-extractor','mom-formatter','mom-review'],
 array['email-dispatch','mom-review'], 6),

('sprint', 'JIRA Sprint and Ticket Analysis',
 'At the end of each sprint, the team needs to understand how the sprint went — how much was completed versus planned, what got stuck, and whether there are patterns worth addressing. This use case generates that analysis automatically.',
 'Sprint reviews and retrospectives require someone to pull data from JIRA, calculate how many story points were completed versus what was planned, identify which tickets were delayed and for how long, and spot whether the same types of issues keep coming up sprint after sprint. Doing this manually takes time and often gets skipped or done superficially. This pipeline pulls sprint data from JIRA covering the current and previous sprints, calculates the team''s velocity and whether it is trending up or down, identifies every ticket that sat in progress for longer than expected, looks across multiple sprints to find recurring patterns — modules that always run late, ticket types that consistently overrun, team members who are carrying a disproportionate load — and produces a clear, readable report with charts and a set of plain-English findings that can be discussed in the sprint review without anyone needing to prepare slides in advance.',
 'exploring', '#2F78C4', 'sprint',
 'A sprint analysis report showing velocity over recent sprints, a list of tickets that were delayed with the cause and owner, recurring patterns identified across sprints, and five to eight plain-English findings ready for a sprint review discussion.',
 array['sprint-fetcher','velocity-analyser','blocker-detector','pattern-agent','insight-summariser','report-gen'],
 array['jira-puller','report-gen','ppt-builder'], 7);

-- ── AGENTS ──────────────────────────────────────────────────
insert into agents (id, name, short_desc, tagline, color, group_id, inputs, outputs, confirmed, sort_order) values

('master-orch', 'Master Orchestrator',
 'The central coordinator that receives every incoming piece of work, decides what needs to happen, and directs the right agents to handle it.',
 'Think of this as the project manager for the entire AI system. Every time a Change Request is raised in JIRA, this agent is the first to see it. It reads the request, determines what work needs to be done — does this require test cases to be written? Does it also need test data? Should automation scripts be generated? — and then activates the correct pipelines in the right order. It monitors the progress of every pipeline running underneath it, and if something fails or gets stuck, it decides whether to retry or escalate to a human. Nothing in the system starts without going through the Master Orchestrator first.',
 '#D97706', 'core',
 array['Incoming JIRA Change Request'],
 array['Work orders to each pipeline','Live status of all running pipelines'],
 false, 1),

('pipeline-orch', 'Pipeline Orchestrator',
 'Manages the internal flow of a single pipeline — running each agent in the right order, handling retries, and reporting back when the job is done.',
 'While the Master Orchestrator oversees all pipelines at a high level, the Pipeline Orchestrator sits inside each individual pipeline and manages the detail. It runs each agent in the correct sequence, waits for each one to finish before triggering the next, and passes the output of one agent as the input to the next. If the Quality Reviewer rejects a draft, the Pipeline Orchestrator manages the retry — it sends the draft back to the Generator with the specific feedback, waits for the revised output, and puts it back through review. It allows a maximum of two retry rounds before deciding that a human needs to step in. Every use case has its own Pipeline Orchestrator running the agents within it.',
 '#7373D8', 'core',
 array['Work order from Master Orchestrator'],
 array['Completed pipeline output','Escalation signal if human review is needed'],
 false, 2),

('jira-connector', 'JIRA Connector Agent',
 'Connects to JIRA and retrieves every piece of information from a Change Request — the requirements, acceptance criteria, linked tickets, and any attachments.',
 'When a Change Request is created in JIRA, it contains everything a developer or analyst wrote about the change — what is being built, what the business rules are, what the acceptance conditions are, what other tickets it is related to. This agent connects to JIRA, pulls all of that content for a given CR number, and converts it from raw JIRA data into a clean, structured format that the next agent can work with.',
 '#2E308E', 'p1',
 array['Change Request number','JIRA login credentials'],
 array['All CR fields extracted and structured'],
 true, 3),

('cr-summarizer', 'CR Summarizer Agent',
 'Reads through the full Change Request and distils it into a focused summary containing only what a test writer needs — the scope, the business rules, and the conditions that require testing.',
 'A Change Request is written for developers and project managers, not test designers. It typically contains version history, approval trails, background context, and a lot of content that is not directly relevant to writing test cases. This agent reads through everything and extracts only the parts that matter for testing.',
 '#2E308E', 'p1',
 array['Full CR content from JIRA Connector'],
 array['Focused testing summary — scope, impacted modules, business rules, testable conditions, edge cases'],
 false, 4),

('rag-retrieval', 'RAG Retrieval Agent',
 'Searches through all the test case Excel files the team has written historically, finds the ones most relevant to the current Change Request, and brings them as reference material for the generator.',
 'RAG stands for Retrieval-Augmented Generation. This agent takes the CR summary and searches through every test case Excel file the team has produced, selecting the most relevant examples to guide the generator.',
 '#2E308E', 'p1',
 array['CR summary','Library of historical test case Excel files'],
 array['The five to ten most relevant past test cases as reference context'],
 false, 5),

('designer-memory', 'Designer Memory Agent',
 'Builds and maintains a personal profile for each test designer, learning their preferences and working style over time.',
 'Two test designers looking at the same Change Request will often produce different test cases — not because one is right and the other wrong, but because each person has developed their own way of thinking about testing. This agent maintains a profile for each designer that records their preferences and feedback from past sessions.',
 '#0AA8AC', 'p1',
 array['Designer profile from previous sessions','Short pre-run conversation with the designer'],
 array['Personalised context note for the Generator','Updated designer profile saved for future sessions'],
 false, 6),

('tc-generator', 'Test Case Generator Agent',
 'Writes the actual test cases — drawing on the CR summary, the historical examples retrieved, and the designer''s known preferences.',
 'This is the agent that does the writing. By the time it runs, it has everything it needs: the CR summary, a set of historical test cases showing how this team writes, and a note from the Designer Memory Agent on the particular designer''s preferences.',
 '#2E308E', 'p1',
 array['CR summary','Reference test cases from RAG Retrieval','Designer preferences from Designer Memory Agent'],
 array['A draft set of test cases — ID, module, scenario, steps, expected result, priority, test type'],
 true, 7),

('quality-reviewer', 'Quality Reviewer Agent',
 'Checks the drafted test cases against the quality of historical work and the designer''s preferences — approving them or sending them back with precise notes.',
 'Generating test cases is one thing. Making sure they are good is another. This agent compares the draft against historical test cases and the designer''s profile, checking coverage, structure, and detail level.',
 '#2E308E', 'p1',
 array['Draft test cases','Historical test cases as benchmark','Designer preferences'],
 array['Approved draft passed forward, or specific refinement notes sent back to Generator'],
 false, 8),

('designer-feedback', 'Designer Feedback Agent',
 'Presents the quality-approved test cases to the test designer for a final review, collects their feedback, and records anything new they say.',
 'The AI can only do so much on its own. This agent makes sure the designer''s knowledge gets captured. It presents the approved test case draft to the designer and has a short conversation: does this look right? Is anything missing?',
 '#0AA8AC', 'p1',
 array['Quality-approved draft test cases'],
 array['Test cases with designer sign-off','Updated designer profile with new feedback'],
 false, 9),

('parser-formatter', 'Parser and Formatter Agent',
 'Takes the signed-off test cases and produces a properly formatted Excel file with all the correct columns, IDs, and structure.',
 'After the designer has reviewed and approved the test cases, this agent produces the final deliverable in the format the team uses. It maps the confirmed content precisely into the standard Excel structure.',
 '#2E308E', 'p1',
 array['Designer-approved test cases'],
 array['Fully formatted output Excel file — all columns, ready for use or for Pipeline 2'],
 false, 10),

('tc-reader', 'Test Case Reader Agent',
 'Opens the test case Excel file and works out exactly what data each test case requires in order to be executed.',
 'A test case tells you what to test and how. But to actually run it, you need the data to go with it. This agent reads every test case and for each one determines what data fields are needed.',
 '#0AA8AC', 'p2',
 array['Test case Excel file from Pipeline 1'],
 array['Data requirements list — for each test case, the specific fields needed to execute it'],
 true, 11),

('db-lookup', 'DB Lookup Agent',
 'Connects to the backend systems — BSCS, CRM, and ODS — and retrieves real, valid data values for each test case.',
 'This is where the test data comes from — not invented or estimated, but pulled from the actual systems the testing will run against. The agent receives the list of data requirements and queries the appropriate backend system for each field.',
 '#0AA8AC', 'p2',
 array['Data requirements list from Test Case Reader'],
 array['Real data values — MSISDN numbers, SIM references, port codes, dealer IDs, account details'],
 true, 12),

('xml-builder', 'XML Builder Agent',
 'Assembles the XML message that the order management system expects, combining the test case details with the live data values fetched from the backend.',
 'To create a test customer account in the system, you need to submit a specific XML message — the CreateFixedLineOrder request — which contains all the account details in exactly the right structure and format.',
 '#0AA8AC', 'p2',
 array['Test case details','Live data values from DB Lookup Agent'],
 array['A complete CreateFixedLineOrder XML payload for each test case'],
 true, 13),

('eai-push', 'EAI Push Agent',
 'Submits the XML payload to the order management endpoint and captures the response — confirming the test account was created.',
 'This agent is the one that actually creates the test account in the system. It takes the completed XML payload and sends it to the EAI endpoint — the same API the production system uses to process customer orders.',
 '#0AA8AC', 'p2',
 array['CreateFixedLineOrder XML payload'],
 array['EAI system response — order ID, request ID, and account code on success; error details on failure'],
 true, 14),

('data-validator', 'Data Validator Agent',
 'Checks whether the system accepted the request successfully — and if not, identifies different data to use and tries again.',
 'Not every submission will succeed on the first attempt. An MSISDN might already be in use. A port number might be temporarily unavailable. This agent checks the response and retries with alternative data if needed.',
 '#0AA8AC', 'p2',
 array['EAI response from Push Agent'],
 array['Confirmed valid data on success, or a request for alternative values if the submission failed'],
 true, 15),

('data-writer', 'Data Writer Agent',
 'Takes all the confirmed test data and writes it into the correct cells of the test case Excel file.',
 'Every test case has now been through the data generation process. This agent opens the Excel file from Pipeline 1 and writes each data value into the correct row and column.',
 '#0AA8AC', 'p2',
 array['Confirmed data values','Test case Excel from Pipeline 1'],
 array['Complete output Excel — all test cases with all test data filled in and ready to execute'],
 false, 16),

('automability-checker', 'Automability Checker Agent',
 'Reads through each test case and determines whether it is suitable for automation, requires a human to run it, or can be partially automated.',
 'Not all test cases should be turned into automation scripts. Some require a human to make a visual judgment. Some depend on physical hardware or real-world timing that a script cannot replicate.',
 '#7373D8', 'p3',
 array['Complete test case Excel from Pipeline 2'],
 array['The same Excel with each test case labelled Automatable, Manual, or Partial'],
 false, 17),

('script-generator', 'Script Generator Agent',
 'Writes Robot Framework automation scripts for every automatable test case, working through them in focused batches of five to maintain quality.',
 'For every test case labelled as automatable, this agent writes a complete Robot Framework script. Scripts are written in batches of five at a time for consistent quality.',
 '#7373D8', 'p3',
 array['Automatable test cases with test data from Excel'],
 array['Robot Framework script files — one complete script per automatable test case'],
 true, 18),

('path-resolver', 'Path Resolver Agent',
 'Reads the screen source code and page objects to replace script placeholders with real element locators and paths.',
 'The Script Generator produces Robot Framework scripts with placeholder references. This agent takes those placeholder scripts and the actual source code of the application being tested, and replaces every placeholder with the real path.',
 '#7373D8', 'p3',
 array['Scripts with placeholders from Script Generator','Screen source code or page object files'],
 array['Complete scripts with real element locators replacing all placeholders'],
 true, 19),

('syntax-validator', 'Syntax Validator Agent',
 'Reviews every generated script for correctness — proper structure, no missing variables, correct keyword usage, and accurate references to the test data.',
 'A script containing an error will not run. This agent checks every script the Generator produces before it moves further, verifying syntax, keywords, variable definitions, and data references.',
 '#7373D8', 'p3',
 array['Draft Robot Framework scripts from Generator'],
 array['Verified error-free scripts, or specific issues flagged for human review'],
 false, 20),

('tester-feedback', 'Tester Feedback Agent',
 'The tester runs the uploaded scripts — if they pass the pipeline is done, if they fail the agent captures the error and sends it back to the Script Generator.',
 'Once scripts are uploaded to JIRA, the tester runs them against the application. If a script fails, the Tester Feedback Agent captures the exact failure details and sends them back to the Script Generator.',
 '#9333EA', 'p3',
 array['Script execution result from tester — pass or fail with error details'],
 array['Pipeline complete on pass, or refined script re-uploaded to JIRA on fail'],
 true, 21),

('jira-puller', 'JIRA Data Puller Agent',
 'Connects to JIRA and pulls the current state of all tickets or defects matching a given filter — shared across DSR Reports, Sprint Analysis, and Defect Identification.',
 'Three use cases in this system need data from JIRA. Rather than each use case building its own JIRA connection, this single agent handles all JIRA data retrieval and is shared across all three.',
 '#1D9E5C', 'other',
 array['JIRA filter configuration and date range'],
 array['A structured snapshot of all matching JIRA tickets'],
 true, 22),

('delta-calc', 'Delta Calculator Agent',
 'Compares today''s JIRA data against the previous day''s snapshot to identify precisely what changed.',
 'The Daily Status Report is not about listing everything in JIRA. It is about what changed today. This agent takes two snapshots — today''s data and the previous day''s — and produces a specific change summary.',
 '#1D9E5C', 'other',
 array['Today''s JIRA snapshot','Previous day''s saved snapshot'],
 array['A precise change delta — what moved, what is new, what is delayed, what is blocked'],
 false, 23),

('dsr-narrative', 'DSR Narrative Agent',
 'Converts the change delta into three to five plain-English sentences describing the day''s progress.',
 'Numbers and data lists do not communicate well in a status report. This agent takes the change delta and writes a natural-language summary covering the key points.',
 '#1D9E5C', 'other',
 array['Change delta from Delta Calculator'],
 array['Three to five plain-English sentences summarising the day''s progress'],
 false, 24),

('ppt-builder', 'PPT Builder Agent',
 'Opens the standard DSR PowerPoint template and fills in the current date, ticket status counts, and the written summary.',
 'The team has a fixed PowerPoint template for the Daily Status Report. This agent opens the template, locates each field that needs filling, and fills each one with today''s data.',
 '#1D9E5C', 'other',
 array['DSR PowerPoint template','Today''s counts and narrative'],
 array['Completed DSR PowerPoint with today''s date, status counts, and narrative filled in'],
 false, 25),

('email-dispatch', 'Email Dispatch Agent',
 'Attaches the completed file to an email and sends it to everyone on the distribution list, with the subject line generated automatically.',
 'The final step in the DSR and meeting minutes pipelines. This agent takes the completed file and sends it to the configured recipients with an automatically generated subject line.',
 '#1D9E5C', 'other',
 array['Completed report or minutes file','Configured distribution list'],
 array['Email sent to all recipients with the file attached and an auto-generated subject line'],
 true, 26),

('audio-ingestion', 'Audio Ingestion Agent',
 'Accepts a recorded meeting audio file or a set of typed notes and routes the input to the correct next agent.',
 'The starting point for the meeting minutes pipeline. This agent accepts either an audio recording or typed notes, and routes to the appropriate next agent.',
 '#DC2626', 'other',
 array['Audio recording file or plain text meeting notes'],
 array['Input routed to the appropriate next agent'],
 false, 27),

('transcription', 'Transcription Agent',
 'Converts the meeting audio recording into a written transcript of everything that was spoken.',
 'This agent listens to the meeting recording and produces a written transcript of everything said, from start to finish.',
 '#DC2626', 'other',
 array['Meeting audio recording file'],
 array['A complete written transcript of the meeting'],
 false, 28),

('speaker-id', 'Speaker Identifier Agent',
 'Goes through the transcript and adds labels showing who was speaking at each point, using the meeting attendee list as a reference.',
 'A raw transcript is a single block of text with no indication of who said what. This agent uses the list of meeting attendees to label each section with the name of the person who was speaking.',
 '#DC2626', 'other',
 array['Raw transcript','List of meeting attendees'],
 array['Transcript with speaker names added at each change of speaker'],
 false, 29),

('mom-extractor', 'MOM Extractor Agent',
 'Reads through the labelled transcript and pulls out all content that belongs in the minutes — who attended, what was discussed, decisions made, actions agreed, and questions left open.',
 'This agent turns a conversation into structured meeting minutes. It reads through the full transcript and extracts everything that matters: attendees, topics discussed, decisions made, every action item with its owner and due date, and questions not resolved.',
 '#DC2626', 'other',
 array['Speaker-labelled transcript or typed meeting notes'],
 array['Structured meeting content — attendees, topics, decisions, action items with owners and due dates, open questions'],
 false, 30),

('mom-formatter', 'MOM Formatter Agent',
 'Takes the structured meeting content and lays it out in the standard minutes-of-meeting format the team uses.',
 'The extracted meeting content is organised but unformatted. This agent applies the standard meeting minutes template — date, attendees, agenda summary, decisions, and an action items table.',
 '#DC2626', 'other',
 array['Structured meeting content from MOM Extractor'],
 array['Formatted minutes document in the team''s standard layout, ready for review'],
 false, 31),

('mom-review', 'Review and Send Agent',
 'Shares the draft minutes with the meeting organiser for a final check, then sends the confirmed minutes to all attendees.',
 'Before the minutes go to everyone, the meeting organiser verifies them. This agent sends the formatted draft to the organiser only, awaiting their confirmation before distributing to all attendees.',
 '#DC2626', 'other',
 array['Formatted minutes document'],
 array['Meeting minutes sent to all attendees after organiser confirmation'],
 false, 32),

('sprint-fetcher', 'Sprint Data Fetcher Agent',
 'Pulls all sprint data from JIRA for the current sprint and the previous several sprints.',
 'Sprint analysis requires historical data. This agent fetches data for the current sprint and the previous three to five completed sprints.',
 '#2F78C4', 'other',
 array['JIRA project and sprint range configuration'],
 array['Structured data for the current and previous sprints — story points, ticket statuses, assignees, dates'],
 true, 33),

('velocity-analyser', 'Velocity Analyser Agent',
 'Calculates the team''s sprint velocity over recent cycles and identifies whether delivery performance is improving, declining, or consistent.',
 'Velocity tells you whether the team is getting through roughly the work they plan each sprint, and whether that is getting better or worse.',
 '#2F78C4', 'other',
 array['Multi-sprint data from Sprint Data Fetcher'],
 array['Velocity trend — completion rate per sprint and direction of change'],
 false, 34),

('blocker-detector', 'Blocker Detector Agent',
 'Finds every ticket that has been in progress or blocked for longer than expected, with the ticket details, how long it has been waiting, and who currently owns it.',
 'In any sprint, tickets slow down without anyone formally flagging them as blocked. This agent identifies those tickets systematically.',
 '#2F78C4', 'other',
 array['Sprint ticket data including status history and timestamps'],
 array['List of delayed tickets — each with ID, current status, days in that status, and current assignee'],
 true, 35),

('pattern-agent', 'Pattern Recognition Agent',
 'Looks across multiple sprints to identify recurring issues — modules that consistently run late, ticket types that always overrun, or workload imbalances.',
 'Individual sprint data tells you what happened in that sprint. Data across multiple sprints tells you what consistently happens — which is far more useful.',
 '#2F78C4', 'other',
 array['Multi-sprint data from Sprint Data Fetcher'],
 array['Recurring patterns — which modules, ticket types, or team members appear consistently in delays'],
 false, 36),

('insight-summariser', 'Insight Summariser Agent',
 'Takes all the analysis and writes it as a set of clear, specific, plain-English observations a manager can read and discuss without any preparation.',
 'Analysis agents produce data and findings. This agent turns those findings into something immediately useful — five to eight specific observations in plain language.',
 '#2F78C4', 'other',
 array['Velocity trend','Blocker list','Patterns from Pattern Recognition'],
 array['Five to eight plain-English insight statements ready for a sprint review'],
 false, 37),

('report-gen', 'Report Generator Agent',
 'Produces a formatted report bringing together the charts, data, and plain-English findings from the analysis pipeline into a single shareable document.',
 'The final step in both Sprint Analysis and Defect Identification. This agent formats all analysis into a document — charts, data tables, and the plain-English insight statements.',
 '#2F78C4', 'other',
 array['Analysis outputs and insight statements from preceding agents'],
 array['Formatted Excel or PowerPoint report with charts, tables, and findings'],
 false, 38),

('hpsm-jira-fetcher', 'JIRA / HPSM Fetcher Agent',
 'Reads the test cases and PDI document from the JIRA or HPSM ticket — whichever system the incident was logged in.',
 'PDI incidents are raised in either JIRA or HPSM. This agent connects to both systems, reads the relevant ticket, and retrieves the test cases and PDI document.',
 '#9333EA', 'other',
 array['JIRA or HPSM ticket reference'],
 array['Test cases and PDI document extracted from the ticket'],
 true, 39),

('rca-analyser', 'RCA Analyser Agent',
 'Cross-references the test cases and PDI document, identifies the root cause, assesses which modules are affected, and surfaces any recurring patterns.',
 'This is where the analysis happens. The agent reads the PDI document and the associated test cases side by side — understanding what was being tested, what failed, and why.',
 '#9333EA', 'other',
 array['Test cases and PDI document from JIRA / HPSM'],
 array['Structured analysis findings — root cause, affected modules, patterns'],
 true, 40),

('rca-report-gen', 'RCA Report Generator Agent',
 'Produces the detailed RCA analysis report and posts it back to the original JIRA and HPSM ticket.',
 'Takes all the findings from the RCA Analyser and produces a structured, detailed report, then posts it directly back into both the JIRA and HPSM tickets.',
 '#9333EA', 'other',
 array['Structured analysis findings from RCA Analyser'],
 array['Detailed RCA report posted back to JIRA and HPSM'],
 true, 41),

('ticket-writer', 'JIRA / HPSM Writer Agent',
 'Posts the RCA analysis report back to both the originating JIRA ticket and the HPSM incident.',
 'Every pipeline in this system produces an output that needs to go somewhere. This agent handles posting completed files back to both JIRA and HPSM tickets.',
 '#0AA8AC', 'other',
 array['Output file to post','JIRA or HPSM ticket reference','Target system (JIRA, HPSM, or both)'],
 array['File attached or comment posted on the specified JIRA and/or HPSM ticket'],
 true, 42),

('jira-writer', 'JIRA Writer Agent',
 'Uploads the output file — Test Plan or updated Test Plan — directly to the originating JIRA ticket as an attachment.',
 'Once the Test Plan is ready, this agent takes the completed file and attaches it to the correct JIRA ticket, adding a comment that notes what was uploaded, which pipeline produced it, and when.',
 '#2F78C4', 'other',
 array['Completed Test Plan file','JIRA ticket reference'],
 array['Test Plan attached to the JIRA ticket with a timestamped comment'],
 true, 43);

-- ── AGENT STEPS ─────────────────────────────────────────────
insert into agent_steps (agent_id, step_number, step_name, step_desc, is_special, sort_order) values
-- master-orch
('master-orch','1','Detect incoming work','Reads new or updated Change Requests from JIRA as they arrive.',false,1),
('master-orch','2','Decide what is needed','Determines which combination of pipelines to run — test cases only, test data too, automation scripts, or all three.',false,2),
('master-orch','3','Route to the correct pipelines','Activates the relevant pipelines in the correct sequence, passing each one the information it needs.',false,3),
('master-orch','4','Monitor until complete','Tracks every pipeline and steps in if any agent fails or a human decision is required.',false,4),
-- pipeline-orch
('pipeline-orch','1','Receive the work order','Gets the task and all necessary inputs from the Master Orchestrator.',false,1),
('pipeline-orch','2','Run each agent in order','Triggers each agent one at a time, waits for it to complete, and passes the output to the next.',false,2),
('pipeline-orch','3','Manage retries','If a quality check fails, sends the output back with specific feedback and tries again. Maximum two rounds.',false,3),
('pipeline-orch','4','Report when done','Tells the Master Orchestrator that the pipeline is complete, or that a human needs to review something.',false,4),
-- jira-connector
('jira-connector','1','Connect to JIRA','Authenticates with the JIRA instance.',false,1),
('jira-connector','2','Pull all CR fields','Retrieves the full content — summary, description, requirements, acceptance criteria, linked tickets, and attachments.',false,2),
('jira-connector','3','Structure the output','Converts the raw JIRA response into a clean format ready for the Summarizer Agent.',false,3),
-- cr-summarizer
('cr-summarizer','1','Read the full CR','Takes all content retrieved by the JIRA Connector Agent.',false,1),
('cr-summarizer','2','Identify what matters for testing','Extracts scope, impacted modules, business rules, edge cases, and acceptance criteria.',false,2),
('cr-summarizer','3','Produce a focused summary','A clear, concise summary containing only the information the Test Case Generator needs.',false,3),
-- rag-retrieval
('rag-retrieval','1','Understand the CR context','Reads the CR summary to identify the module, type of change, and business area.',false,1),
('rag-retrieval','2','Search historical test files','Scans all stored test case Excel files for scenarios matching the current CR context.',false,2),
('rag-retrieval','3','Select the best matches','Ranks results and selects the most relevant examples.',false,3),
('rag-retrieval','4','Pass everything forward','Sends the CR summary together with the selected reference test cases to the Generator.',false,4),
-- designer-memory
('designer-memory','1','Load the designer profile','Retrieves stored preferences and feedback from this designer''s previous sessions.',false,1),
('designer-memory','2','Ask a brief question','One focused question: is there anything specific to focus on for this Change Request?',false,2),
('designer-memory','3','Build the context note','Combines the stored profile with today''s input into a context note for the Generator.',false,3),
('designer-memory','★','Update after review','Any new feedback from the designer is captured and added permanently to their profile.',true,4),
-- tc-generator
('tc-generator','1','Gather all inputs','Brings together the CR summary, historical references, and designer preferences.',false,1),
('tc-generator','2','Write test cases in batches','Fifteen to twenty at a time for consistent quality.',false,2),
('tc-generator','3','Check for obvious gaps','Reviews the draft for missing scenarios before sending for formal review.',false,3),
('tc-generator','4','Send to Quality Reviewer','Passes the complete draft to the Quality Reviewer Agent.',false,4),
-- quality-reviewer
('quality-reviewer','1','Load quality benchmarks','Retrieves historical test cases to understand the expected quality standard.',false,1),
('quality-reviewer','2','Check coverage and structure','Verifies all requirements are tested, edge cases are included, and style matches designer preferences.',false,2),
('quality-reviewer','3','Approve or request refinement','Approves if quality is sufficient. If not, writes specific improvement notes and returns to Generator.',false,3),
('quality-reviewer','4','Escalate if unresolved','After two rounds with insufficient quality, flags for human review.',false,4),
-- designer-feedback
('designer-feedback','1','Present the draft to the designer','Shows the approved test cases to the designer in a readable format.',false,1),
('designer-feedback','2','Collect feedback','Asks: does this cover everything? Is there anything to add or adjust?',false,2),
('designer-feedback','3','Save new insights','Any new preferences or corrections are saved permanently to the designer''s profile.',false,3),
('designer-feedback','4','Confirm and pass forward','Designer confirms the output is ready and the test cases move to the Formatter.',false,4),
-- parser-formatter
('parser-formatter','1','Receive approved test cases','Takes the confirmed content from the Designer Feedback Agent.',false,1),
('parser-formatter','2','Map to the Excel structure','Assigns content to each column: Test ID, Module, Scenario, Steps, Expected Result, Priority, Type, Requirement.',false,2),
('parser-formatter','3','Generate and save the file','Produces the final clean Excel file ready for the testing team or Pipeline 2.',false,3),
-- tc-reader
('tc-reader','1','Open the test case Excel','Reads all rows from the Pipeline 1 output file.',false,1),
('tc-reader','2','Identify data requirements per test case','Determines which data fields are needed for each test case.',false,2),
('tc-reader','3','Produce the requirements list','A structured list mapping each test case to its data needs.',false,3),
-- db-lookup
('db-lookup','1','Receive the requirements list','Gets the list of what data each test case needs.',false,1),
('db-lookup','2','Query the correct system','Connects to BSCS, CRM, or ODS depending on the data type needed.',false,2),
('db-lookup','3','Return the values','Passes real, validated data values to the XML Builder Agent.',false,3),
-- xml-builder
('xml-builder','1','Receive inputs','Test case details and real data values from the DB Lookup Agent.',false,1),
('xml-builder','2','Assemble the XML','Builds the CreateFixedLineOrder message with all fields correctly populated.',false,2),
('xml-builder','3','Pass to EAI Push Agent','Completed payload handed to the agent that will submit it.',false,3),
-- eai-push
('eai-push','1','Submit to EAI endpoint','Sends the XML payload to the configured order management API.',false,1),
('eai-push','2','Capture the response','Records the full system response — order number, request ID, account code, or error message.',false,2),
('eai-push','3','Pass to Data Validator','Sends the response to the Validator Agent to check the outcome.',false,3),
-- data-validator
('data-validator','1','Check the system response','Was a valid order number and account code returned?',false,1),
('data-validator','2','Retry with different data if needed','If the submission was rejected, requests alternative values from DB Lookup and tries again.',false,2),
('data-validator','3','Confirm the data','Once a successful response is received, marks the data as validated and ready to write.',false,3),
-- data-writer
('data-writer','1','Open the test case Excel','Loads the file produced by Pipeline 1.',false,1),
('data-writer','2','Write data to each row','Inserts each validated value into the correct column of the corresponding test case row.',false,2),
('data-writer','3','Save the complete file','The final Excel with all test cases and test data, ready for use or Pipeline 3.',false,3),
-- automability-checker
('automability-checker','1','Read each test case','Goes through every row in the Excel file.',false,1),
('automability-checker','2','Assess the steps','Determines whether the steps can be replicated reliably by a script.',false,2),
('automability-checker','3','Label each row','Marks each test case Automatable, Manual, or Partial.',false,3),
-- script-generator
('script-generator','1','Select automatable cases','Takes only the test cases labelled Automatable or Partial.',false,1),
('script-generator','2','Write scripts in batches of five','One Robot Framework script per test case, five at a time for consistent quality.',false,2),
('script-generator','3','Pass each batch for validation','Each completed batch goes to the Syntax Validator before moving to the next.',false,3),
-- path-resolver
('path-resolver','1','Receive placeholder scripts','Gets the generated scripts from the Script Generator Agent.',false,1),
('path-resolver','2','Read screen source code','Loads the application source code or page object files to find real element locators.',false,2),
('path-resolver','3','Map and replace','Matches each placeholder to its correct element path and replaces it throughout the script.',false,3),
('path-resolver','4','Pass to Validator','Resolved scripts passed to Syntax Validator for checking.',false,4),
-- syntax-validator
('syntax-validator','1','Receive each batch of scripts','Gets the scripts from the Generator Agent.',false,1),
('syntax-validator','2','Check structure and keywords','Verifies correct syntax, keyword usage, variable definitions, and test data references.',false,2),
('syntax-validator','3','Correct or flag issues','Fixes simple errors automatically. Flags anything more complex for human attention.',false,3),
-- tester-feedback
('tester-feedback','1','Receive execution result','Tester runs the scripts and the result — pass or fail — is fed back.',false,1),
('tester-feedback','2','On pass — confirm complete','Pipeline marked complete. Result recorded.',false,2),
('tester-feedback','3','On fail — capture and send back','Exact failure details captured and sent to Script Generator with instructions to refine.',false,3),
('tester-feedback','4','Learn from feedback','Builds a profile of recurring failure types to improve script quality over time.',false,4),
-- jira-puller
('jira-puller','1','Connect to JIRA','Authenticates with the JIRA instance.',false,1),
('jira-puller','2','Execute the filter','Runs the configured JIRA filter for the relevant use case.',false,2),
('jira-puller','3','Return the snapshot','All matching tickets with statuses, assignees, dates, and descriptions.',false,3),
-- delta-calc
('delta-calc','1','Load the previous snapshot','Reads the data saved at the end of the previous working day.',false,1),
('delta-calc','2','Compare ticket by ticket','Identifies status changes, newly created tickets, newly completed items, tickets that stopped progressing.',false,2),
('delta-calc','3','Produce the delta summary','A specific, factual summary of what changed.',false,3),
-- dsr-narrative
('dsr-narrative','1','Read the change delta','Takes the factual change summary from the Delta Calculator.',false,1),
('dsr-narrative','2','Write the narrative','Produces three to five sentences describing what changed — what progressed, what was raised, what is blocked.',false,2),
('dsr-narrative','3','Pass to PPT Builder','The narrative is ready to be inserted into the DSR PowerPoint.',false,3),
-- ppt-builder
('ppt-builder','1','Open the template','Loads the standard DSR PowerPoint template.',false,1),
('ppt-builder','2','Fill in each field','Inserts today''s date, ticket status counts, and the narrative into the correct positions.',false,2),
('ppt-builder','3','Save the completed file','Saves the finished presentation for the Email Dispatch Agent.',false,3),
-- email-dispatch
('email-dispatch','1','Receive the completed file','Takes the final file from the preceding agent.',false,1),
('email-dispatch','2','Generate the subject line','Creates a descriptive subject including the date and a key headline from the content.',false,2),
('email-dispatch','3','Send to the distribution list','Emails the file to all configured recipients.',false,3),
-- audio-ingestion
('audio-ingestion','1','Accept the input','Receives either an audio file or a text document.',false,1),
('audio-ingestion','2','Determine the format','Checks whether the input is audio or text.',false,2),
('audio-ingestion','3','Route to the correct agent','Audio goes to Transcription. Text goes directly to MOM Extractor.',false,3),
-- transcription
('transcription','1','Load the audio file','Reads the recorded meeting file.',false,1),
('transcription','2','Convert speech to text','Processes the full audio and produces a written transcript of everything said.',false,2),
('transcription','3','Pass to Speaker Identifier','The raw transcript is handed to the next agent for speaker labelling.',false,3),
-- speaker-id
('speaker-id','1','Load the attendee list','Gets the list of people in the meeting.',false,1),
('speaker-id','2','Identify speakers','Uses name mentions and context to determine who was speaking at each point.',false,2),
('speaker-id','3','Label the transcript','Adds speaker names before each section of speech.',false,3),
-- mom-extractor
('mom-extractor','1','Read the full transcript','Goes through the complete meeting content.',false,1),
('mom-extractor','2','Extract structured content','Identifies: attendees, topics covered, decisions made, action items with owner and due date, unresolved questions.',false,2),
('mom-extractor','3','Output the structured content','Passes the organised content to the MOM Formatter Agent.',false,3),
-- mom-formatter
('mom-formatter','1','Apply the template','Maps the extracted content onto the standard minutes layout.',false,1),
('mom-formatter','2','Build the action items table','One row per action item: responsible person, task, and due date.',false,2),
('mom-formatter','3','Produce the formatted document','Complete minutes ready for the Review and Send Agent.',false,3),
-- mom-review
('mom-review','1','Send draft to organiser','Emails the formatted minutes to the meeting organiser only.',false,1),
('mom-review','2','Wait for confirmation','Organiser reviews and either confirms or makes corrections.',false,2),
('mom-review','3','Send to all attendees','Once confirmed, sends the final minutes to everyone who attended.',false,3),
-- sprint-fetcher
('sprint-fetcher','1','Connect to JIRA','Uses the shared JIRA Data Puller Agent with sprint-specific configuration.',false,1),
('sprint-fetcher','2','Fetch sprint history','Retrieves data for the current sprint and the previous three to five completed sprints.',false,2),
('sprint-fetcher','3','Return structured data','Story points planned and completed per sprint, statuses, assignees, and dates.',false,3),
-- velocity-analyser
('velocity-analyser','1','Calculate velocity per sprint','Story points completed divided by story points planned gives the completion rate.',false,1),
('velocity-analyser','2','Identify the trend','Is velocity improving, declining, or stable across recent sprints?',false,2),
('velocity-analyser','3','Flag anomalies','Highlights sprints significantly lower than the recent average.',false,3),
-- blocker-detector
('blocker-detector','1','Check the age of each ticket','For every in-progress or blocked ticket, calculates how long it has been in that state.',false,1),
('blocker-detector','2','Flag tickets over threshold','Marks anything older than the configured number of days.',false,2),
('blocker-detector','3','Produce the blocker list','Returns ticket ID, current status, age, and assignee for each flagged item.',false,3),
-- pattern-agent
('pattern-agent','1','Analyse across all sprints','Looks at the full dataset across the retrieved sprint history.',false,1),
('pattern-agent','2','Group and compare','Groups tickets by module, type, and assignee, and compares delay rates.',false,2),
('pattern-agent','3','Surface the patterns','Identifies which groups consistently appear in delays and passes findings forward.',false,3),
-- insight-summariser
('insight-summariser','1','Gather all findings','Collects outputs from Velocity Analyser, Blocker Detector, and Pattern Recognition Agent.',false,1),
('insight-summariser','2','Write plain-English observations','For each significant finding, one clear statement describing what happened and what it means.',false,2),
('insight-summariser','3','Pass to Report Generator','Insight statements passed to the Report Generator.',false,3),
-- report-gen
('report-gen','1','Collect all analysis','Gathers all outputs from the pipeline.',false,1),
('report-gen','2','Build charts and tables','Trend charts, frequency tables, and heatmaps from the data.',false,2),
('report-gen','3','Assemble the report','Charts, tables, and insight text combined into a clean formatted document.',false,3),
-- hpsm-jira-fetcher
('hpsm-jira-fetcher','1','Identify the source system','Determines whether the ticket is in JIRA or HPSM.',false,1),
('hpsm-jira-fetcher','2','Connect and retrieve','Connects to the correct system and reads the full ticket — the PDI document and associated test cases.',false,2),
('hpsm-jira-fetcher','3','Pass to RCA Analyser','Both the PDI doc and test cases are handed together to the next agent.',false,3),
-- rca-analyser
('rca-analyser','1','Read PDI doc and test cases together','Cross-references what was being tested against what actually failed.',false,1),
('rca-analyser','2','Classify root cause','Assigns the RCA category: Requirement Gap, Code Defect, Environment Issue, Test Data Problem, or Configuration Error.',false,2),
('rca-analyser','3','Assess impact','Identifies other modules that share the affected area and test cases that should be re-verified.',false,3),
('rca-analyser','4','Find patterns','Looks across all PDIs in scope to identify recurring root causes or problem areas.',false,4),
-- rca-report-gen
('rca-report-gen','1','Structure the report','Organises the findings into a clear format: root cause, affected modules, test cases to re-verify, and pattern highlights.',false,1),
('rca-report-gen','2','Post to JIRA','Attaches the completed report to the originating JIRA ticket.',false,2),
('rca-report-gen','3','Post to HPSM','Attaches the same report to the HPSM ticket — both systems updated simultaneously.',false,3),
-- ticket-writer
('ticket-writer','1','Receive the output and ticket reference','Gets the completed file and the ID of the ticket it should be posted to.',false,1),
('ticket-writer','2','Identify the target system','Determines whether to post to JIRA, HPSM, or both.',false,2),
('ticket-writer','3','Connect and post','Attaches the file to the ticket and adds a structured comment noting what was uploaded, the pipeline that produced it, and the timestamp.',false,3),
-- jira-writer
('jira-writer','1','Receive the file and ticket reference','Gets the completed Test Plan and the ID of the JIRA ticket it belongs to.',false,1),
('jira-writer','2','Connect to JIRA','Authenticates with the JIRA instance.',false,2),
('jira-writer','3','Attach and comment','Uploads the file as an attachment and posts a structured comment: what was uploaded, which pipeline produced it, and the timestamp.',false,3);
